<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="dslab.mailbox.MailboxStartsecureTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2022-01-14T14:07:24" hostname="leonardo" time="4.067">
  <properties/>
  <testcase name="sendStartsecure" classname="dslab.mailbox.MailboxStartsecureTest" time="4.067"/>
  <system-out><![CDATA[accepted client
DmtpClientConnection start Socket[addr=/127.0.0.1,port=42586,localport=13652]
DmapClientConnection start Socket[addr=/127.0.0.1,port=53624,localport=13653]
DmapClientConnection start Socket[addr=/127.0.0.1,port=53626,localport=13653]
DmapClientConnection finished Socket[addr=/127.0.0.1,port=53624,localport=13653]
Client Answer: wTZqUdwD6RIWtgTrvoYecJgulKRQVActTzbaW7u4i0puTak8ymlUHmvVQGT6wCUVoByDaF3dEhRFku5uC4kap9yd2FntrtIcuftaf36WSU/Qg2ue254TiEVmCLILd2eef8SxHh6U0hyWwXPdD+BHBplzrBeIIiTPqLteKKHl6veEzuEh+s/u66hcyPG+3t18C4ZR1jo50VZhAa9Kfqeuj787llQTZMMv+2gEIRciKPu8pF5/57+hmOmcp+mAoBaK0XdjTZ1Win4bF1CP44sdHLgKy2BfvGn69RN7ThWBEu8fXuBsxcflhLDus1OIlDv8YgoLVGiOCamtZf0TtqcErg==
RSA answer: ok iHMrqvRt48s4g8Zj5QgmOVh7OFXHwtXOv/I+/Zp0s+0= lq0Ci/wsbHgHdfI5s+hDP7UqMOp1alBvw9hSemZdn0M= z18ARkgxra4kNhYgyjK7Xg==
ok iHMrqvRt48s4g8Zj5QgmOVh7OFXHwtXOv/I+/Zp0s+0=
MailboxDmtpListenerThread finished
MailboxDmapListenerThread finished
should be ok: ok
DmapClientConnection finished Socket[addr=/127.0.0.1,port=53626,localport=13653]
]]></system-out>
  <system-err><![CDATA[Jan 14, 2022 3:07:24 PM dslab.mailbox.MailboxServerProtocolTest setUp
INFO: Waiting for server sockets to appear
java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
	at java.rmi/sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
	at dslab.mailbox.MailboxServer.run(MailboxServer.java:75)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/java.net.Socket.<init>(Socket.java:454)
	at java.base/java.net.Socket.<init>(Socket.java:231)
	at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
	... 6 more
]]></system-err>
</testsuite>
